name: Build for MIPSLE with Docker

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clean up disk space
        run: |
          sudo apt-get clean
          docker rmi $(docker images -q) || true
          df -h

      - name: Build with Docker
        run: |
          docker run --rm -v "$PWD":/work -w /work \
            messense/rust-musl-cross:mipsel-linux-musl \
            cargo build --target mipsel-unknown-linux-musl --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dysk-mipsle
          path: target/mipsel-unknown-linux-musl/release/dysk

      - name: Debug on failure
        if: failure()
        run: |
          docker images
          df -h
          ls -la target/mipsel-unknown-linux-musl/release/
