name: Build for MIPSLE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clean up disk space
        run: |
          sudo apt-get clean
          sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc /swapfile
          df -h

      - name: Setup Rust with mirror
        env:
          RUSTUP_DIST_SERVER: https://mirrors.tuna.tsinghua.edu.cn/rust-static
          RUSTUP_UPDATE_ROOT: https://mirrors.tuna.tsinghua.edu.cn/rust-static/rustup
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
          source $HOME/.cargo/env
          echo "[source.crates-io]" >> $HOME/.cargo/config
          echo "replace-with = 'tuna'" >> $HOME/.cargo/config
          echo "[source.tuna]" >> $HOME/.cargo/config
          echo "registry = \"https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git\"" >> $HOME/.cargo/config
          rustup target add mipsel-unknown-linux-musl
          rustc --version
          cargo --version

      - name: Install MIPSLE toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-mipsel-linux-gnu musl-tools

      - name: Cache cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build with cross
        run: |
          source $HOME/.cargo/env
          cargo build --target mipsel-unknown-linux-musl --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dysk-mipsle
          path: target/mipsel-unknown-linux-musl/release/dysk

      - name: Debug on failure
        if: failure()
        run: |
          rustup show
          ls -la $HOME/.rustup
          df -h
          cargo tree
