name: Build for MIPSLE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clean up disk space
        run: |
          sudo apt-get clean
          docker rmi $(docker images -q) || true
          df -h
          
      - name: Update rustup
        run: rustup self update
      - name: Install Rust with mirror
        env:
          RUSTUP_DIST_SERVER: https://mirrors.ustc.edu.cn/rust-static
          RUSTUP_UPDATE_ROOT: https://mirrors.ustc.edu.cn/rust-static/rustup
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
          source $HOME/.cargo/env
          rustup target add mipsel-unknown-linux-musl
          rustc --version
          cargo --version

      - name: Install cross
        run: cargo install cross

      - name: Build with cross
        run: cross build --target mipsel-unknown-linux-musl --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dysk-mipsle
          path: target/mipsel-unknown-linux-musl/release/dysk

      - name: Debug on failure
        if: failure()
        run: |
          rustup show
          ls -la $HOME/.rustup
          df -h
